# Generated by Django 5.0.1 on 2024-02-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='病院名')),
                ('address', models.CharField(max_length=200, verbose_name='住所')),
                ('phone_number', models.CharField(max_length=15, verbose_name='電話番号')),
            ],
        ),
    ]
