# Generated by Django 5.0.1 on 2024-02-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='is_primary_care',
            field=models.BooleanField(default=False),
        ),
    ]
