# Generated by Django 5.0.1 on 2024-02-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_medicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='hospital',
            name='department',
            field=models.CharField(default='General', max_length=100, verbose_name='診療科目'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='is_primary_care',
            field=models.BooleanField(default=False, verbose_name='かかりつけ医'),
        ),
    ]
