# Generated by Django 5.0.1 on 2024-02-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_hospital_address_remove_hospital_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='is_primary_care',
        ),
        migrations.AlterField(
            model_name='hospital',
            name='department',
            field=models.CharField(max_length=150, verbose_name='診療科目'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=150, verbose_name='病院名'),
        ),
    ]
