# Generated by Django 5.0.1 on 2024-02-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_hospital_is_primary_care_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='is_primary_care',
            field=models.BooleanField(default=False),
        ),
    ]
