# Generated by Django 5.0.1 on 2024-02-07 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_hospital_is_primary_care'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='is_primary_care',
        ),
    ]
