# Generated by Django 5.0.1 on 2024-02-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_hospital_is_primary_care'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='診療科目名')),
            ],
        ),
        migrations.AlterField(
            model_name='hospital',
            name='department',
            field=models.CharField(max_length=200, verbose_name='診療科目'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=200, verbose_name='病院名'),
        ),
    ]
