# Generated by Django 5.0.1 on 2024-02-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_department_alter_hospital_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='department',
        ),
        migrations.AddField(
            model_name='hospital',
            name='departments',
            field=models.ManyToManyField(to='myapp.department', verbose_name='診療科目'),
        ),
    ]
