# Generated by Django 5.0.1 on 2024-02-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_hospital_department_hospital_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='departments',
            field=models.ManyToManyField(related_name='hospitals', to='myapp.department', verbose_name='診療科目'),
        ),
    ]
