# Generated by Django 5.0.1 on 2024-02-08 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_hospital_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='departments',
        ),
        migrations.AddField(
            model_name='department',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='myapp.hospital'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
