# Generated by Django 5.0.1 on 2024-02-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_hospital_departments_department_hospital_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='hospital',
        ),
        migrations.AddField(
            model_name='hospital',
            name='departments',
            field=models.ManyToManyField(to='myapp.department'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
