# Generated by Django 5.0.1 on 2024-02-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_department_hospital_hospital_departments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='departments',
        ),
        migrations.AddField(
            model_name='hospital',
            name='department',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
