# Generated by Django 5.0.1 on 2024-02-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_hospital_is_primary_care'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='departments',
            field=models.ManyToManyField(related_name='hospitals', to='myapp.department'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='department',
            field=models.CharField(max_length=100),
        ),
    ]
