# Generated by Django 5.0.1 on 2024-02-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_event_date_remove_medicine_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
