# Generated by Django 5.0.1 on 2024-02-21 04:11

import django.db.models.deletion
from django.db import migrations, models


def fix_invalid_department(apps, schema_editor):
    Department = apps.get_model('myapp', 'Department')
    Hospital = apps.get_model('myapp', 'Hospital')
    # `小児科`に対応するDepartmentオブジェクトを取得します。
    # 存在しない場合は、新しいDepartmentオブジェクトを作成します。
    pediatric_department, _ = Department.objects.get_or_create(name='小児科')
    # すべてのHospitalオブジェクトのdepartmentフィールドを、
    # 上で取得または作成した`小児科`のDepartmentオブジェクトに設定します。
    Hospital.objects.all().update(department=pediatric_department)


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department'),
        ),
        migrations.RunPython(fix_invalid_department),
    ]
